server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/alexandre-agendamentos
    username: postgres
    password: alexandre22
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true

logging:
  level:
    com.ead.course: DEBUG
